### PR TITLE
Converted token utilities to Cairo 2.X

### PR DESCRIPTION
**Pull request by dbejarano820**
WIP

### CODE REVIEW

**Comment by omarespejel** [comment]
Hey @dbejarano820! Let me know if you need support in anything :)

**Comment by dbejarano820** [comment]
@omarespejel I sent you a message on telegram!

**Comment by dbejarano820** [comment]
@ codeWhizperer thoughts on latest commit?

**Comment by dbejarano820** [comment]
@codeWhizperer thoughts on latest commit?

**Comment by dbejarano820** [comment]
I believe we should hold onto this update until the new component syntax is added to cairo for inheritance. It's a WIP

**Comment by gyan0890** [comment]
Hey @dbejarano820 : Checking for a quick update on this. I am looking to expedite this tutorial, so that we can use this for our upcoming basecamp :). Let me know if you need any help with the tutorial.

**Pull request closed without merging**
