### PR TITLE
Spanish translation of the contracts

### PR DESCRIPTION
**Pull request by omarespejel**
## Description
Translation to Spanish of contracts tutorials. This will allow the community to translate into a specific folder called `Spanish`. This could later be replicated in the Portuguese-speaking community.

## Actions
* Created the Spanish directory to store everything related to Spanish
* Translated the ex 01 contract.
* Moved `README.es.md` to `Spanish/README.md`.

## Who can review?
- @drspacemn @l-henri @LucasLvy @barretodavid  - does this structure makes sense to you?

### CODE REVIEW

**Comment by barretodavid** [comment]
In my opinion, duplicating the smart contracts on different language folders increases the overhead of maintaining this repository too much for little gain (think about updates to the code). I'm all up for translating the README to different languages but I think we should have a single source of truth for the smart contracts even if that leaves in-line comments in English. I'm curious to hear what @LucasLvy, @drspacemn and @l-henri  think about this.

**Comment by omarespejel** [comment]
Yes, this is true:
* The bad: overhead cost of having to update the code.
* The good: engagement with the Spanish-speaking community.

Maybe Spanish speakers not fluent in English can use Google Translate to better understand docs and tutorials.

**Comment by l-henri** [comment]
Agree with David 

Envoyé de mon iPhone

**Comment by omarespejel** [comment]
Makes sense! Thanks, @barretodavid @l-henri. Due to the community's interest in having this repo in Spanish, we will do the translations in a separate repo outside `starknet-edu`.

**Pull request closed without merging**
